export const actionTypes = {
    SET_POKEMON: 'SET_POKEMON',
    CLEAN_UP: 'CLEAN_UP',
    SELECTED_POKEMON: 'SELECTED_POKEMON',
    REMOVE_SELECTED_POKEMON: 'REMOVE_SELECTED_POKEMON',
    SET_URL: 'SET_URL',
    NEXT_URL: 'NEXT_URL',
    PREV_URL: 'PREV_URL',
}